### ISSUE TITLE
SDLFileType does not implement <NSMutableCopying> protocol

### ISSUE THREAD

**Issue by tomhoag** [smartdevicelink/SmartDeviceLink-iOS#126] opened 2015-03-19 21:13 UTC
In SDLRPCRequest Factory, ```+(SDLPutFile*) buildPutFileWithFileName:fileType:persisistentFile:correlationID``` attempts to create a mutable copy of fileType.  SDLFileType or its super class SDLEnum do not implement the ```NSMutableCopying``` protocol.

```
+(SDLPutFile*) buildPutFileWithFileName:(NSString*) syncFileName fileType:(SDLFileType*) fileType persisistentFile:(NSNumber*) persistentFile correlationID:(NSNumber*) correlationID {
    
    //TODO
    //    +(FMPutFile*) buildPutFile:(NSString*) syncFileName fileType:(SDLFileType*) fileType persisistentFile:(NSNumber*) persistentFile fileData:(NSData*) fileData correlationID:(NSNumber*) correlationID {
    
    SDLPutFile* msg = [[SDLPutFile alloc] init];
    msg.syncFileName = syncFileName;
    
    msg.fileType =  [fileType mutableCopy];
    msg.persistentFile = persistentFile;
    msg.correlationID = correlationID;
    
    return msg;
}
```

**Comment by joeljfischer** [comment] 2015-03-20 13:20
Duplicate of #80

**Closed by joeljfischer** 2015-03-20 13:20 UTC
